### ISSUE TITLE
Come up with a name/URL for this project

### ISSUE THREAD

**Issue by ErnieAtLYD** [codeforamerica/mdc-feedback#130]
It can't be "https://mdc-feedback-stage.herokuapp.com" forever. Who wants to own this? @mathias-gibson?

**Comment by mathias-gibson** [comment]
i can own it, but I'll probably need to organize a brainstorming sesh on it:

step - step, flow, map
feedback - loop, follothru,

**Comment by phiden** [comment]
Eh on bastardized spellings in the name of being cute, so I'd veto follothru, even though I like how it sounds and I recognize that "followthrough" isn't as visually catchy. Adding a 'w', though --  followthru? 

I like the idea of loop, but I think that's too generic. MDCLoop? DadeLoop? CountyLoop? /shrug

For STEP: PermitFlow, EventFlow, something flow.

**Comment by mathias-gibson** [comment]
for the dashboard, we could just be straightforward and call it MDC PIC Dashboard, MDC Building Dashboard

for step, is step not good enough itself, since the acronym happens to be apt for a wizard/workflow? OD we want something more generic and less specific to special events? (or go with something about a journey/process/path/guide/sherpa/compass/tour/stream/rudder, maybe guidebook or pathway?

**Comment by phiden** [comment]
PGH is using Sherpa, so not that. Plus it has some vaguely racist undertones, apparently.
