### ISSUE TITLE
sketch up plans tracking metrics

### ISSUE THREAD

**Issue by mathias-gibson** [codeforamerica/mdc-feedback#280]

**Comment by ErnieAtLYD** [comment]
For context for @phiden: we are getting push back, both by ITD and now by Mike, for implementation of this. I'm assuming it's because of the complexity of the DB tables that ITD delivered to CIAO. Initial response was "can we kill this please" but some push back from us he wants to understand _exactly_ what widgets are needed and how we get and calculate these metrics so stakeholders can understand what we're to build.

**Comment by phiden** [comment]
Wait, didn't the County _ask_ for these metrics?

**Comment by mathias-gibson** [comment]
yeah, @ErnieAtLYD says ITD and Mike want to see exactly what we are building to make sure we're not asking for more data than we need. Also, wouldnt be bad to show to lourdes and christa to make sure its what they want. the point being they say its a big lift and want to make sure its worth it

**Comment by phiden** [comment]
Right, I got that. What I meant was, didn’t we decide to push for Plans data on the basis of people in the County asking for Plans data in the dashboard? As opposed to of our own volition?

**Comment by mathias-gibson** [comment]
most definitely, its key for the metrics that christa and lourdes asked for

**Comment by mathias-gibson** [comment]
@ErnieAtLYD so these are what have been asked for:
- number of times a plan is re-submitted to each section/team/discipline/trade (could be histogram)
- % of plans that are resubmitted for the section/team/discipline/trade (could be pie chart)
- comments made by section/team/discipline when rejecting plans (word cloud or table?)
- avg time in each section/team/discipline (number)
- amount of time a plan is with the customer vs the county while in plan review (number)

I think they would be displayed as numbers, but if there is space we could use a viz.

**Comment by ErnieAtLYD** [comment]
I'd like more details.

> number of times a plan is re-submitted to each section/team/discipline/trade (could be histogram)

Average number of times over the past 7 days? 30 days? 6 months? That e-mail had literally 50-75 groups, because some groups had DERM had A-Teams, etc. Do we include those? Or just the most popular? What constitutes the most popular?

> % of plans that are resubmitted for the section/team/discipline/trade (could be pie chart)

So I'm assuming that all the re-submitted plans would be put into a grouping and then we would build a pie chart out of that. If a plan is re-submitted twice, is this counted twice? You have "section/team/discipline/trade". Going back to that thing where some groups had specialized teams - how does that fit into this? Does all this mean there will be one pie chart or many?

> avg time in each section/team/discipline (number)

I'm okay with that, but again: there are like a LOT of groups if we are accounting for that e-mail. Does that mean pages and pages of numbers? Some of them? How do we choose?

> amount of time a plan is with the customer vs the county while in plan review (number)

This is the one I can actually see the most clearly - since we have a number already for the average time from application date to issuance, we can just mark a subset of that as "in plans."

**Comment by ErnieAtLYD** [comment]
Also, note the more detailed you are in writing out specs or requirements,
the less necessary back and forth is required. I need all use cases at
least considered- not just for high level considerations but for
implementation asks, otherwise developers make assumptions that aren't
often correct.

**Comment by mathias-gibson** [comment]
these are good questions. im just thinking through these as i go, dont have the answers when im writing them initially, but asking good questions is helpful for us to think through the technical challenges:

"number of times a plan is re-submitted to each section/team/discipline/trade (could be histogram)"

ideally the time frame for all metrics would be dynamic, with 3-4 options or a calendar widget, Im not sure what would be best in this case. it actually will probably be too detailed to show each plan's number of resubmittals. christa has asked for this by trade/discipline, so we should ask her what groupings make sense.

"% of plans that are resubmitted for the section/team/discipline/trade (could be pie chart)"

this would be the number of plans with a re-submittal / total number of plans for each trade (again we would defer to christa for meaning groupings of trades). so there would be ~7-10 pie charts or %s

"avg time in each section/team/discipline (number)"

like the above, defer to christa, guessing 7-10 numbers, however she sees them being meaningfully grouped
